from __future__ import absolute_import

print("")
print("Customized nnU-Net by Chenghao Liu. The following changes were made:")
print("==============")
print("== TRAINING ==")
print("==============")
print("* disabled data unpacking to speed up training (reduced IO).")
print("* changed default training epochs from 1000 to 300.")
print("* changed 'pin_memory' to 'False'.")
print("* when fold='all', 20% of the training samples will be randomly selected and used in validation.")
print("* 'nnUNetTrainerV2' now support manually setting the number of training epochs and batches (use '-b' and '-e').")
print("* add '--noval' to tell the program not use validation set during training.")
print("* use '--custom_val_cases XXX YYY ...' and set fold to 'all' to manually assign validation set cases.")
print("* use '--save_every_epoch' to save models from all epochs.")
print("* add '--softmax' to save softmax values of validation set samples.")
print("===============")
print("== INFERENCE ==")
print("===============")
print("* add '--selected_cases XXX YYY ...' when inference will only predict the selected test subjects (XXX YYY ...) .")
print("* add '--softmax' to save softmax values of test set samples.")
print("============")
print("== OTHERS ==")
print("============")
print("* removed unused codes.")
print("* minor bug fixes...")
print("")

from . import *

